spring:
  application:
    name: eureka-server2
server:
  port: 8762                   # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: peer2
    instance-id: ${spring.application.name}:${server.port}
    #${spring.application.name}:${server.port}
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
