spring:
  application:
    name: eureka-server1
  output:
    ansi:
      enabled: always
server:
  port: 8761                    # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: peer1
    instance-id: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
#      defaultZone: http://localhost:8761/eureka/


