server:
  port: 9001
spring:
  application:
    name: webclient-consumer
  output:
    ansi:
      enabled: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
  instance:
    prefer-ip-address: true